---
# tasks file for packages


- name: install the latest version of Apache
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - httpd
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'


- name: install the latest version of Apache
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - apache2
  when: ansible_distribution == 'Debian' and ansible_distribution == 'Ubuntu'
